#!/usr/bin/env bash
# skill-report.sh — skill-evaluation dashboard and report helpers

set -euo pipefail

if [[ -z "${SKILL_EVALUATION_LIB_DIR:-}" ]]; then
  SKILL_EVALUATION_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
fi

if ! declare -f get_all_skill_statistics > /dev/null 2>&1; then
  # shellcheck source=hooks/lib/skill-metrics.sh
  source "${SKILL_EVALUATION_LIB_DIR}/skill-metrics.sh"
fi

skill_dashboard_status_marker() {
  local rate="${1:-0}"

  if awk -v rate="$rate" 'BEGIN {exit !(rate >= 0.9)}'; then
    echo "✅"
  elif awk -v rate="$rate" 'BEGIN {exit !(rate >= 0.7)}'; then
    echo "⚠️"
  else
    echo "❌"
  fi
}

# Markdown 대시보드 생성
# Usage: generate_skill_dashboard <project_root> [days]
generate_skill_dashboard() {
  local project_root="${1:-}"
  local days="${2:-30}"
  local metrics_dir stats dashboard_file total_skills total_exec overall_rate unused

  metrics_dir=$(skill_metrics_dir "$project_root")
  dashboard_file=$(skill_dashboard_file_path "$project_root")
  mkdir -p "$metrics_dir"

  stats=$(get_all_skill_statistics "$project_root" "$days")

  cat > "$dashboard_file" << 'EOF'
# Skill Evaluation Dashboard

EOF

  total_skills=$(echo "$stats" | jq -r '.summary.total_skills')
  total_exec=$(echo "$stats" | jq -r '.summary.total_executions')
  overall_rate=$(echo "$stats" | jq -r '.summary.overall_success_rate')
  {
    echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo "Period: Last ${days} days"
    echo ""
    echo "## Summary"
    echo ""
    echo "| Metric | Value |"
    echo "|--------|-------|"
    echo "| Total Skills | $total_skills |"
    echo "| Total Executions | $total_exec |"
    echo "| Overall Success Rate | $(awk -v rate="$overall_rate" 'BEGIN {printf "%.1f%%", rate * 100}') |"
    echo ""
    echo "## Skill Statistics"
    echo ""
    echo "| Skill | Executions | Success Rate | Avg Duration | Status |"
    echo "|-------|------------|--------------|--------------|--------|"
  } >> "$dashboard_file"

  while IFS=$'\t' read -r skill exec rate dur; do
    local pct dur_ms status_marker
    pct=$(awk -v rate="$rate" 'BEGIN {printf "%.1f", rate * 100}')
    dur_ms=$(awk -v dur="$dur" 'BEGIN {printf "%.0f ms", dur}')
    status_marker=$(skill_dashboard_status_marker "$rate")
    echo "| $skill | $exec | ${pct}% | ${dur_ms} | $status_marker |" >> "$dashboard_file"
  done < <(echo "$stats" | jq -r '.skills[] | select(.total_executions > 0) | [.skill, .total_executions, .success_rate, .avg_duration_ms] | @tsv')

  unused=$(echo "$stats" | jq -r '.skills[] | select(.total_executions == 0) | .skill')
  echo "" >> "$dashboard_file"

  if [[ -n "$unused" ]]; then
    {
      echo "## Unused Skills"
      echo ""
    } >> "$dashboard_file"
    while IFS= read -r skill; do
      [[ -n "$skill" ]] || continue
      echo "- $skill" >> "$dashboard_file"
    done < <(printf '%s\n' "$unused")
    echo "" >> "$dashboard_file"
  fi

  {
    echo "## Top Errors"
    echo ""
    echo "$stats" | jq -r '.skills[] | select(.top_errors | length > 0) | .top_errors[]? | "- \(.message) (\(.count) occurrences)"' 2> /dev/null | head -10
    echo ""
    echo "---"
    echo "*Auto-generated by skill-evaluation.sh*"
  } >> "$dashboard_file"

  echo "$dashboard_file"
}

# 권장사항 생성
generate_recommendations() {
  local stats="${1:-}"
  local recs="" low_success unused item_number

  item_number=1
  low_success=$(echo "$stats" | jq -r '.skills[] | select(.success_rate < 0.7 and .total_executions >= 5) | .skill')
  if [[ -n "$low_success" ]]; then
    recs+="${item_number}. **Review failing skills:**\n"
    while IFS= read -r skill; do
      [[ -n "$skill" ]] || continue
      recs+="   - $skill\n"
    done < <(printf '%s\n' "$low_success")
    item_number=$((item_number + 1))
  fi

  unused=$(echo "$stats" | jq -r '.skills[] | select(.total_executions == 0) | .skill')
  if [[ -n "$unused" ]]; then
    recs+="${item_number}. **Consider removing unused skills:**\n"
    while IFS= read -r skill; do
      [[ -n "$skill" ]] || continue
      recs+="   - $skill\n"
    done < <(printf '%s\n' "$unused" | head -3)
  fi

  if [[ -z "$recs" ]]; then
    recs="- All skills performing well ✅"
  fi

  printf '%b' "$recs"
}

# 주간 리포트 생성
# Usage: generate_weekly_report <project_root>
generate_weekly_report() {
  local project_root="${1:-}"
  local metrics_dir report_file stats_7d

  metrics_dir=$(skill_metrics_dir "$project_root")
  report_file="${metrics_dir}/weekly_report_$(date +%Y%m%d).md"
  mkdir -p "$metrics_dir"

  stats_7d=$(get_all_skill_statistics "$project_root" "7")

  cat > "$report_file" << EOF
# Weekly Skill Evaluation Report

**Generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')

## Summary (Last 7 Days)

| Metric | Value |
|--------|-------|
| Total Executions | $(echo "$stats_7d" | jq -r '.summary.total_executions') |
| Success Rate | $(echo "$stats_7d" | jq -r '.summary.overall_success_rate | . * 100 | floor')% |

## Top Performers

$(echo "$stats_7d" | jq -r '.skills | sort_by(-.success_rate) | .[0:3] | .[] | "- \(.skill): \(.success_rate * 100 | floor)% success rate"')

## Needs Attention

$(echo "$stats_7d" | jq -r '.skills | sort_by(.success_rate) | .[0:3] | .[] | "- \(.skill): \(.success_rate * 100 | floor)% success rate"')

## Recommendations

$(generate_recommendations "$stats_7d")

---
*Auto-generated by skill-evaluation.sh*
EOF

  echo "$report_file"
}
